services:
  postgres:
    image: postgres:15-alpine
    container_name: dueled-postgres-dev
    environment:
      POSTGRES_DB: dueled
      POSTGRES_USER: dueled_user
      POSTGRES_PASSWORD: dueled_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"  # Use port 5433 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init:/docker-entrypoint-initdb.d
      - ./server/database/migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dueled_user -d dueled"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: dueled-redis-dev
    ports:
      - "6380:6379"  # Use port 6380 to avoid conflicts
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local